# ===============================================================================================================
# Plot a food tree generated without using the FilterDBByDiet or Check.db functions.
# Version 1
# Created on 02/08/2023 by Rie Sadohara
# 06/26/2023 replaced "OTU" with "IFC".
# ===============================================================================================================

# Set your working directory as the main directory (dietary_patterns)
# Session --> Set working directory --> Choose directory.
setwd("/Users/gabriellavondohlen/Desktop/Greathouse/VitaminDstudy/DietR_package")

# Name your main directory for future use.
main_wd <- file.path(getwd())

# You can plot foodtrees you generated by using the ggtree package.
# If you have not downloaded and installed the ggtree package yet:
# You can do so by first installing BiocManager (if you have not done so):
if (!require("BiocManager", quietly = TRUE))install.packages("BiocManager")

# Then, use BiocManager to install the "ggtree" package.
# --> BiocManager::install("ggtree")

# The documentation for the ggtree package can be found in the developer's GitHub page
# (https://guangchuangyu.github.io/software/ggtree/).


# Load the functions necessary to set directories.
library(ggtree)
source("GitHub_tutorial/DietR/lib/specify_data_dir.R")
source("GitHub_tutorial/DietR/lib/viz_food_tree.r")

diet_colors <- c('#e89c54', '#d06c5c', '#f0c4b4', '#a0bca4', '#a8bccc', '#d8dce4')

# ===============================================================================================================
  # Plot foodtrees
# ===============================================================================================================
# Go to the "Foodtree" directory where the tree files are saved.
# SpecifyDataDirectory(directory.name = "eg_data/VVKAJ/Foodtree")

# Load the generated food tree. This will load the .nwk file and save it as a tree object called "tree".
# It is OK to see a message saying:
# Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
# Also defined by 'tidytree'
tree <- read.tree("AJdata/Foodtree/MCTs_23887_Items_f_id_s_m_QCed_4Lv.tree.nwk")

# Prepare node labels of L1 for plotting. It assumes that the tree file has 9 L1 levels.
PrepFoodTreePlots(input.tree=tree)

# Create a color-coded and annotated food tree with nine L1 levels.
# It is OK to see some warning messages about Coordinate system and scale for 'y' already being present.
VizFoodTree(input.tree=tree, layout="circular")

### this is the whole function: 
tree_an_hi <- ggtree(tree, ladderize=F, layout = "circular") +
  geom_hilight(   node=L1nodenum[1],  fill=diet_colors[1]) +  # Milk products
  geom_cladelabel(node=L1nodenum[1], color=  diet_colors[1], label=L1nodelabels[1], offset=0.5, geom="label", fill='white', hjust=0.5) + 
  geom_hilight(   node=L1nodenum[2],  fill=diet_colors[5]) +  # Meat & fish
  geom_cladelabel(node=L1nodenum[2], color=  diet_colors[5], label=L1nodelabels[2], offset=0.5, geom="label", fill='white', hjust=0.5) + 
  geom_hilight(   node=L1nodenum[3],  fill=diet_colors[2]) +  # Eggs
  geom_cladelabel(node=L1nodenum[3], color=  diet_colors[2], label=L1nodelabels[3], offset=0.5, geom="label", fill='white', hjust=0.5) +  
  geom_hilight(   node=L1nodenum[4],  fill=diet_colors[4]) +  # Legumes, nuts & seeds
  geom_cladelabel(node=L1nodenum[4], color=  diet_colors[4], label=L1nodelabels[4], offset=0.5, geom="label", fill='white', hjust=0.5) + 
  geom_hilight(   node=L1nodenum[5],  fill=diet_colors[1]) +  # Grain products
  geom_cladelabel(node=L1nodenum[5], color=  diet_colors[1], label=L1nodelabels[5], offset=0.5, geom="label", fill='white', hjust=0.5) + 
  geom_hilight(   node=L1nodenum[6],  fill=diet_colors[5]) +  # Fruits
  geom_cladelabel(node=L1nodenum[6], color=  diet_colors[5], label=L1nodelabels[6], offset=0.5, geom="label", fill='white', hjust=0.5) +
  geom_hilight(   node=L1nodenum[7],  fill=diet_colors[2]) +  # Vegetables
  geom_cladelabel(node=L1nodenum[7], color=  diet_colors[2], label=L1nodelabels[7], offset=0.5, geom="label", fill='white', hjust=0.5) + 
  geom_hilight(   node=L1nodenum[8],  fill=diet_colors[4]) +  # Fats & oils
  geom_cladelabel(node=L1nodenum[8], color=  diet_colors[4], label=L1nodelabels[8], offset=0.5, geom="label", fill='white', hjust=0.5) + 
  geom_hilight(   node=L1nodenum[9],  fill=diet_colors[1]) +  # Sweets & beverages
  geom_cladelabel(node=L1nodenum[9], color=  diet_colors[1], label=L1nodelabels[9], offset=0.5, geom="label", fill='white', hjust=0.5) 

# Widen the opening of the tree  
tree_an_hi_o <- open_tree(tree_an_hi, 10)

# Rotate the tree so that the root (break) will come to the bottom
tree_an_hi_o_rt <- rotate_tree(tree_an_hi_o, 275) # 270 + 10*0.5 

### end of whole function

# Save the tree as a PDF file.
ggsave("output/MCTs_23887_Items_f_id_s_m_QCed_4Lv.tree.jpeg",
       annotated_tree, device="jpeg", width=6, height=6, units="in", dpi=300)

# You can also visualize trees of different levels; Lv2, Lv3, etc., which corresponds to the classification depth
# of each food item in the dataset. For example, Lv3 contains L1, L2, and L3 categories of food; whereas Lv4
# contains L1, L2, L3, and L4 categories. Thus, as the level goes deeper, the more internal nodes there will
# be in the food tree.

# ---------------------------------------------------------------------------------------------------------------

tree <- read.tree("VDMTdata/Foodtree/asa24_Items_f_id_s_m_QCed_4Lv.tree.nwk")
PrepFoodTreePlots(input.tree=tree)
# VizFoodTree(input.tree=tree, layout="circular")
tree_an_hi <- ggtree(tree, ladderize=F, layout = "circular") +
  geom_hilight(   node=L1nodenum[1],  fill=diet_colors[1]) +  # Milk products
  geom_cladelabel(node=L1nodenum[1], color=  diet_colors[1], label=L1nodelabels[1], offset=0.5, geom="label", fill='white', hjust=0.5) + 
  geom_hilight(   node=L1nodenum[2],  fill=diet_colors[5]) +  # Meat & fish
  geom_cladelabel(node=L1nodenum[2], color=  diet_colors[5], label=L1nodelabels[2], offset=0.5, geom="label", fill='white', hjust=0.5) + 
  geom_hilight(   node=L1nodenum[3],  fill=diet_colors[2]) +  # Eggs
  geom_cladelabel(node=L1nodenum[3], color=  diet_colors[2], label=L1nodelabels[3], offset=0.5, geom="label", fill='white', hjust=0.5) +  
  geom_hilight(   node=L1nodenum[4],  fill=diet_colors[4]) +  # Legumes, nuts & seeds
  geom_cladelabel(node=L1nodenum[4], color=  diet_colors[4], label=L1nodelabels[4], offset=0.5, geom="label", fill='white', hjust=0.5) + 
  geom_hilight(   node=L1nodenum[5],  fill=diet_colors[1]) +  # Grain products
  geom_cladelabel(node=L1nodenum[5], color=  diet_colors[1], label=L1nodelabels[5], offset=0.5, geom="label", fill='white', hjust=0.5) + 
  geom_hilight(   node=L1nodenum[6],  fill=diet_colors[5]) +  # Fruits
  geom_cladelabel(node=L1nodenum[6], color=  diet_colors[5], label=L1nodelabels[6], offset=0.5, geom="label", fill='white', hjust=0.5) +
  geom_hilight(   node=L1nodenum[7],  fill=diet_colors[2]) +  # Vegetables
  geom_cladelabel(node=L1nodenum[7], color=  diet_colors[2], label=L1nodelabels[7], offset=0.5, geom="label", fill='white', hjust=0.5) + 
  geom_hilight(   node=L1nodenum[8],  fill=diet_colors[4]) +  # Fats & oils
  geom_cladelabel(node=L1nodenum[8], color=  diet_colors[4], label=L1nodelabels[8], offset=0.5, geom="label", fill='white', hjust=0.5) + 
  geom_hilight(   node=L1nodenum[9],  fill=diet_colors[1]) +  # Sweets & beverages
  geom_cladelabel(node=L1nodenum[9], color=  diet_colors[1], label=L1nodelabels[9], offset=0.5, geom="label", fill='white', hjust=0.5) 

# Widen the opening of the tree  
tree_an_hi_o <- open_tree(tree_an_hi, 10)

# Rotate the tree so that the root (break) will come to the bottom
tree_an_hi_o_rt <- rotate_tree(tree_an_hi_o, 275) # 270 + 10*0.5 

tree_an_hi_o_rt
### end of whole function
#annotated_tree
ggsave("output/asa24_Items_f_id_s_m_QCed_4Lv.tree.jpeg",
       annotated_tree, device="jpeg", width=6, height=6, units="in", dpi=300)

