# ===============================================================================================================
# k-means clustering with ASA24 data.
# Version 1
# Created on 01/06/2022 by Rie Sadohara
# ===============================================================================================================

# Set your working directory as to the main directory.
#Session --> Set working directory --> Choose directory.
setwd("/Users/gabriellavondohlen/Desktop/Greathouse/VitaminDstudy/DietR_package")

main_wd <- file.path(getwd())

library(ggfortify)
library(gridExtra)
library(cluster)
library(ggplot2)
library(factoextra)

# Set your ggplot2 theme.
theme_set(theme_bw(base_size = 14))

# Import source code to run the analyses to follow.
source("GitHub_tutorial/DietR/lib/specify_data_dir.R")
source("GitHub_tutorial/DietR/lib/k-means.R")

setwd(main_wd)

# ===============================================================================================================
# Import data from your data directory
# ===============================================================================================================

# In this section, we are going to perform k-means analysis for each of Nutrient as is, Nutrient average,
# Food categories as is, and Food categories average.

# Before proceeding, ensure to have four directories (folders) named as:
#   kmeans_Nut_asis
#   kmeans_Nut_ave
#   kmeans_Cat_asis
#   kmeans_Cat_ave
#
# K-means analysis results will be saved in this folder.  You can change those directory names, but
# if you do so, you will need to modify the directory name, "res_dir_xxx_xxxx", to match your new directory name.

# ===============================================================================================================
# Nutrient data as is, processed for clustering analyses.
# ===============================================================================================================

# Load Nut_asis data.
Tot_m_QCed_Nut_asis_AJ <- read.table(file="AJdata/MCTs_23887_Tot_m_QC_Nut_asis_c_rv.txt",
                                     sep="\t", header=T)
Tot_m_QCed_Nut_asis_VD <- read.table(file="VDMTdata/asa24_Tot_m_QC_Nut_asis_c_rv.txt",
                                     sep="\t", header=T)

# Scale your input file and name it as k-means_input.
kmeans_input_AJ <- scale(Tot_m_QCed_Nut_asis_AJ)
kmeans_input_VD <- scale(Tot_m_QCed_Nut_asis_VD)

# Ensure your input file has the correct number of rows and columns.
dim(kmeans_input_AJ)
dim(kmeans_input_VD)

# Specify the directory (folder) to save the results.
res_dir_nut_asis_AJ = "AJdata/kmeans_Nut_asis"
res_dir_nut_asis_VD = "VDMTdata/kmeans_Nut_asis"

# Specify the prefix of filenames to be saved.
res_prefix_nut_asis_AJ = "MCTs_23887_Nut_asis"
res_prefix_nut_asis_VD = "asa24_Nut_asis"

# Run the elbow, silhouette, and gap methods to find an optimum K (number of clusters).
# Do not alter the name of the input file: kmeans_input. This function below assumes that
# the input is named as "kmeans_input".
# You can only run those three methods for K = 1 through (number of observations - 1).
# The gap method output will be printed on the Console. The gap values are plotted in
# xxx_gapmethod.pdf.
kmeans_input <- kmeans_input_AJ
ChooseK(out.dir= res_dir_nut_asis_AJ, out.prefix= res_prefix_nut_asis_AJ)

# This code will generate three output files all at once in the res_dir_xxx_xxxx:
#
#   Output file postfix    |	File content
#   -------------------    | ---------------------------------------------------------------
#   _elbowmethod.pdf	     |	Shows total within???clusters sum of squares for each K.
#   _gapmethod.pdf	       |	Shows the Gap statistic (k) for each K, and if the factoextra package is used, the optimal K is marked by a dotted line.
#   _silhouettemethod.pdf	 |	Shows the Average silhouette width (~ goodness of fit) for each K, and if the factoextra package is used,
#                                       the optimal K is marked by a dotted line.

# Look at the three figures generated by the ChooseK function above. The elbow and gap methods did not give a
# distinct peak, but the silhouette method gave a peak at K=4. K=2,3,4,5 also have relatively high silhouette
# width (~goodness of fit).

# With specific K values in mind, perform k-means analysis with one specified K. This will save
# Dim1 x Dim2 plot as a .pdf file in your out.dir. Change the filename as necessary.
OneK(myK= 2, out.dir= res_dir_nut_asis_AJ, out.fn = "MCTs_23887_Nut_asis_K2")
oneKplot

# Or try multiple Ks and print the biplots in one panel. Likewise, This will save a Dim1 x Dim2 plot for
# each of the chosen K as a .pdf file in your out.dir. Change the filename to be saved as a PDF as necessary.
# This function uses the factoextra and gridExtra packages.
MultipleK(myKs = c(2,5,7,11), out.dir = res_dir_nut_asis_AJ, out.fn = "MCTs_23887_Nut_asis_K2_5_7_11")
MultipleK(myKs = c(2,3), out.dir = res_dir_nut_asis_AJ, out.fn = "MCTs_23887_Nut_asis_K2-3")


# VDMT
kmeans_input <- kmeans_input_VD
ChooseK(out.dir= res_dir_nut_asis_VD, out.prefix= res_prefix_nut_asis_VD)

OneK(myK= 2, out.dir= res_dir_nut_asis_VD, out.fn = "asa24_Nut_asis_K2")
oneKplot

MultipleK(myKs = c(2,3,4,5), out.dir = res_dir_nut_asis_VD, out.fn = "asa24_Nut_asis_K2-5")

# ===============================================================================================================
# Nutrient data averaged across days, processed for clustering analyses.
# ===============================================================================================================

# Load Nut_ave data.
Tot_m_QCed_Nut_ave_AJ <- read.table(file="AJdata/MCTs_23887_Tot_mean_m_QC_Nut_ave_c_rv.txt", sep="\t", header=T)
Tot_m_QCed_Nut_ave_VD <- read.table(file="VDMTdata/asa24_Tot_mean_m_QC_Nut_ave_c_rv.txt", sep="\t", header=T)

# Scale your input file and name it as k-means_input.
kmeans_input_AJ <- scale(Tot_m_QCed_Nut_ave_AJ)
kmeans_input_VD <- scale(Tot_m_QCed_Nut_ave_VD)

# Ensure your input file has the correct number of rows and columns.
dim(kmeans_input_AJ)
dim(kmeans_input_VD)

# Specify the directory (folder) to save the results.
res_dir_nut_ave_AJ = "AJdata/kmeans_Nut_ave"
res_dir_nut_ave_VD = "VDMTdata/kmeans_Nut_ave"

# Specify the prefix of filenames to be saved.
res_prefix_nut_ave_AJ = "MCTs_23887_Nut_ave"
res_prefix_nut_ave_VD = "asa24_Nut_ave"

# Run elbow, silhouette, and gap methods to find an optimum K (number of clusters).
kmeans_input <- kmeans_input_AJ # this i needed to add! (black box scenario)
ChooseK(out.dir= res_dir_nut_ave_AJ, out.prefix= res_prefix_nut_ave_AJ)

# With specific K values in mind, perform k-means analysis with one specified K.
OneK(myK= 2, out.dir= res_dir_nut_ave_AJ, out.fn = "MCTs_23887_Nut_ave_K2")
oneKplot

# Try multiple Ks and print the biplots in one panel.
MultipleK(myKs = c(2,3,4,5), out.dir = res_dir_nut_ave_AJ, out.fn = "MCTs_23887_Nut_ave_K2-5")
MultipleK(myKs = c(2,3), out.dir = res_dir_nut_ave_AJ, out.fn = "MCTs_23887_Nut_ave_K2-3")


# VD
kmeans_input <- kmeans_input_VD
ChooseK(out.dir= res_dir_nut_ave_VD, out.prefix= res_prefix_nut_ave_VD)

OneK(myK= 2, out.dir= res_dir_nut_ave_VD, out.fn = "asa24_Nut_ave_K2")
oneKplot
MultipleK(myKs = c(2,3), out.dir = res_dir_nut_ave_VD, out.fn = "asa24_Nut_ave_K2-3")

# ===============================================================================================================
# Food categories data as is, processed for clustering analyses.
# ===============================================================================================================

# Load Cat_asis data.
Tot_m_QCed_Cat_asis_AJ <- read.table(file="AJdata/MCTs_23887_Tot_m_QC_Cat_asis_c_rv.txt", sep="\t", header=T)
Tot_m_QCed_Cat_asis_VD <- read.table(file="VDMTdata/asa24_Tot_m_QC_Cat_asis_c_rv.txt", sep="\t", header=T)

# Scale your input file and name it as k-means_input.
kmeans_input_AJ <- scale(Tot_m_QCed_Cat_asis_AJ)
kmeans_input_VD <- scale(Tot_m_QCed_Cat_asis_VD)

# Ensure your input file has the correct number of rows and columns.
dim(kmeans_input_AJ)
dim(kmeans_input_VD)

# Specify the directory (folder) to save the results.
res_dir_cat_asis_AJ = "AJdata/kmeans_Cat_asis"
res_dir_cat_asis_VD = "VDMTdata/kmeans_Cat_asis"

# Specify the prefix of filenames to be saved.
res_prefix_cat_asis_AJ = "MCTs_23887_Cat_asis"
res_prefix_cat_asis_VD = "asa24_Cat_asis"

# Run elbow, silhouette, and gap methods to find an optimum K (number of clusters).
kmeans_input <- kmeans_input_AJ
ChooseK(out.dir= res_dir_cat_asis_AJ, out.prefix= res_prefix_cat_asis_AJ)

# Try multiple Ks and print the biplots in one panel.
MultipleK(myKs = c(2,3), out.dir = res_dir_cat_asis_AJ, out.fn = "MCTs_23887_Cat_asis_K2_3")
MultipleK(myKs = c(6,7), out.dir = res_dir_cat_asis_AJ, out.fn = "MCTs_23887_Cat_asis_K6_7")


# VD
kmeans_input <- kmeans_input_VD
ChooseK(out.dir= res_dir_cat_asis_VD, out.prefix= res_prefix_cat_asis_VD)

MultipleK(myKs = c(2,3), out.dir = res_dir_cat_asis_VD, out.fn = "asa24_Cat_asis_K2_3")

# ===============================================================================================================
# Food categories data averaged across days, processed for clustering analyses.
# ===============================================================================================================

# Load Cat_ave data.
Tot_m_QCed_Cat_ave_AJ <- read.table(file="AJdata/MCTs_23887_Tot_mean_m_QC_Cat_ave_c_rv.txt", sep="\t", header=T)
Tot_m_QCed_Cat_ave_VD <- read.table(file="VDMTdata/asa24_Tot_mean_m_QC_Cat_ave_c_rv.txt", sep="\t", header=T)

# Scale your input file and name it as k-means_input.
kmeans_input_AJ <- scale(Tot_m_QCed_Cat_ave_AJ)
kmeans_input_VD <- scale(Tot_m_QCed_Cat_ave_VD)

# Ensure your input file has the correct number of rows and columns.
dim(kmeans_input_AJ)
dim(kmeans_input_VD)

# Specify the directory (folder) to save the results.
res_dir_cat_ave_AJ = "AJdata/kmeans_Cat_ave"
res_dir_cat_ave_VD = "VDMTdata/kmeans_Cat_ave"

# Specify the prefix of filenames to be saved.
res_prefix_cat_ave_AJ = "MCTs_23887_Cat_ave"
res_prefix_cat_ave_VD = "asa24_Cat_ave"

# Run elbow, silhouette, and gap methods to find an optimum K (number of clusters).
kmeans_input <- kmeans_input_AJ
ChooseK(out.dir= res_dir_cat_ave_AJ, out.prefix= res_prefix_cat_ave_AJ)

# Try multiple Ks and print the biplots in one panel.
MultipleK(myKs = c(2,3,5,6), out.dir = res_dir_cat_ave_AJ, out.fn = "MCTs_23887_Cat_ave_K2_3_5_6")

# With specific K values in mind, perform k-means analysis with one specified K.
OneK(myK= 2, out.dir= res_dir_cat_ave_AJ, out.fn = "MCTs_23887_Cat_ave_K2")
oneKplot


# VD
kmeans_input <- kmeans_input_VD
ChooseK(out.dir= res_dir_cat_ave_VD, out.prefix= res_prefix_cat_ave_VD)

OneK(myK= 2, out.dir= res_dir_cat_ave_VD, out.fn = "asa24_Cat_ave_K2")
oneKplot

MultipleK(myKs = c(2,3), out.dir = res_dir_cat_ave_VD, out.fn = "asa24_Cat_ave_K2_3")

# ---------------------------------------------------------------------------------------------------------------
# Come back to the main directory
setwd(main_wd)
