# Ella von Dohlen 
# Winter 2021 - Spring 2022 
# objective: to fill out the food tree for items in the vitamin D project


# MAKING SENSE OF TAXONOMY LEVELS SO AS TO INFER NEW ONES

library(tidyr)

# setwd("~/Desktop/Greathouse/VitaminDstudy")

# not sure where it originated, but this file came from knights-lab/dietstudy_analyses/data/diet
taxonomy_raw <- read.csv(file = "diet.taxonomy.txt", header = T)

taxonomy_data <- separate(taxonomy_raw,
                     col = FoodID.taxonomy.Main.food.description,
                     into = c('FoodID', 'taxonomy', 'description'),
                     sep = '\t')

#taxonomy_data$taxonomy
taxonomy_data1 <- separate(taxonomy_data,
                     col = taxonomy,
                     into = c('Level1', 'Level2', 'Level3', 'Level4', 'Level5'),
                     sep = ";")

# to find the tree
colnames(taxonomy_data1)
taxonomy_data1[0:6,]
unique(taxonomy_data1$Level1)
unique(taxonomy_data1$Level2[taxonomy_data1$Level1 == "L1_Sugars_Sweets_and_Beverages"])
unique(taxonomy_data1$Level3[taxonomy_data1$Level2 == "L2_Formulated_nutrition_beverages_energy_drinks_sports_drinks_function"])
unique(taxonomy_data1$Level4[taxonomy_data1$Level3 == "L3_"])
unique(taxonomy_data1$Level5[taxonomy_data1$Level4 == "L4_Fruit_juice_drinks_and_fruit_flavored_drinks_fortified_with_calcium"])

unique(taxonomy_data1$Level3[(taxonomy_data1$Level4 == "L4_") & (taxonomy_data1$Level5 == "L5_Sesame_oil")])

unique(taxonomy_data1$Level5[(taxonomy_data1$Level4 == "L4_") & (taxonomy_data1$Level3 == "L3_Regular_salad_dressings")])

FoodIDs <- taxonomy_data1$FoodID
typeof(FoodIDs) #char
split_IDs <- strsplit(FoodIDs, "")


####### ASSIGNING TAX LEVELS ##########
missing_taxonomy_data <- read.csv(file = "Missing_Taxonomy.csv", header = T)
typeof(missing_taxonomy_data$FoodID)
to_assign <- missing_taxonomy_data[!duplicated(missing_taxonomy_data[,"FoodID"]),]
to_assign <- subset(to_assign, select = -FoodAmt)

nrow(to_assign)

#to_assign[1,4] #  "Kefir, NS as to fat content"             - plain yogurt
to_assign[1,5] <- "L1_Milk_and_Milk_Products"
to_assign[1,6] <- "L2_Milks_and_milk_drinks"
to_assign[1,7] <- "L3_Yogurt"
to_assign[1,8] <- "L4_Yogurt_plain"
to_assign[1,9] <- "L5_"

#to_assign[2,4] #  "Almond milk, unsweetened"
#to_assign[3,4] #  "Almond milk, unsweetened, chocolate"
to_assign[2:3,5] <- "L1_Milk_and_Milk_Products"
to_assign[2:3,6] <- "L2_Milks_and_milk_drinks"
to_assign[2:3,7] <- "L3_Milk_fluid_imitation"
to_assign[2:3,8] <- "L4_Milk_almond"
to_assign[2:3,9] <- "L5_"

#to_assign[4,4] #  "Rice milk"                  - milk substitute or rice- Madhur and I talked about this being categorized rice - DONE
to_assign[4,5] <- "L1_Grain_Product"
to_assign[4,6] <- "L2_Pastas_cooked_cereals_rice"
to_assign[4,7] <- "L3_Cooked_cereals_rice"
to_assign[4,8] <- "L4_Cooked_cereals_rice"
to_assign[4,9] <- "L5_Rice"

#to_assign[5,4] #  "Coconut milk"  - "L3_Coconut_beverages" under "L2_Nuts_nut_butters_and_nut_mixtures" OR milk imitation - COCONUT OPTION - DONE
to_assign[5,5] <- "L1_Dry_Beans_Peas_Other_Legumes_Nuts_and_Seeds"
to_assign[5,6] <- "L2_Nuts_nut_butters_and_nut_mixtures"
to_assign[5,7] <- "L3_Coconut_beverages"
to_assign[5,8] <- "L4_"
to_assign[5,9] <- "L5_"

#to_assign[6,4] #  "Yogurt, Greek, NS as to type of milk, plain"
#to_assign[7,4] #  "Yogurt, Greek, whole milk, plain"               # MAKE GREEK YOGURT ANOTHER CATEGORY
#to_assign[8,4] #  "Yogurt, Greek, nonfat milk, plain"
to_assign[6:8,5] <- "L1_Milk_and_Milk_Products"
to_assign[6:8,6] <- "L2_Milks_and_milk_drinks"
to_assign[6:8,7] <- "L3_Yogurt"
to_assign[6:8,8] <- "L4_Yogurt_greek"
to_assign[6:8,9] <- "L5_"

#to_assign[9,4]  #  "Yogurt, Greek, NS as to type of milk, fruit"
#to_assign[10,4] #  "Yogurt, Greek, low fat milk, fruit"
#to_assign[11,4] #  "Yogurt, Greek, nonfat milk, fruit"
to_assign[9:11,5] <- "L1_Milk_and_Milk_Products"
to_assign[9:11,6] <- "L2_Milks_and_milk_drinks"
to_assign[9:11,7] <- "L3_Yogurt"
to_assign[9:11,8] <- "L4_Yogurt_greek_fruit"
to_assign[9:11,9] <- "L5_"

#to_assign[12,4] #  "Yogurt, Greek, NS as to type of milk, flavors other than fruit"
#to_assign[13,4] #  "Yogurt, Greek, whole milk, flavors other than fruit"
#to_assign[14,4] #  "Yogurt, Greek, low fat milk, flavors other than fruit"
to_assign[12:14,5] <- "L1_Milk_and_Milk_Products"
to_assign[12:14,6] <- "L2_Milks_and_milk_drinks"
to_assign[12:14,7] <- "L3_Yogurt"
to_assign[12:14,8] <- "L4_Yogurt_greek"
to_assign[12:14,9] <- "L5_"

#to_assign[15,4] #  "Hot chocolate / Cocoa, ready to drink"
#to_assign[16,4] #  "Hot chocolate / Cocoa, made with dry mix and whole milk"
#to_assign[17,4] #  "Hot chocolate / Cocoa, made with dry mix and reduced fat milk"
#to_assign[18,4] #  "Hot chocolate / Cocoa, made with dry mix and non-dairy milk"
to_assign[15:18,5] <- "L1_Milk_and_Milk_Products"
to_assign[15:18,6] <- "L2_Milks_and_milk_drinks"
to_assign[15:18,7] <- "L3_Flavored_milk_and_milk_drinks_fluid"
to_assign[15:18,8] <- "L4_Chololate_or_other_flavored"
to_assign[15:18,9] <- "L5_"

#to_assign[19,4] #  "Fruit smoothie, with whole fruit and dairy"
#to_assign[20,4] #  "Fruit smoothie juice drink, with dairy"
to_assign[19:20,5] <- "L1_Milk_and_Milk_Products"
to_assign[19:20,6] <- "L2_Milks_and_milk_drinks"
to_assign[19:20,7] <- "L3_Flavored_milk_and_milk_drinks_fluid"
to_assign[19:20,8] <- "L4_Milk_fruit_smoothie"
to_assign[19:20,9] <- "L5_"

#to_assign[21,4] #  "Coffee creamer, liquid, fat free, sugar free, flavored"
to_assign[21,5] <- "L1_Milk_and_Milk_Products"
to_assign[21,6] <- "L2_Milks_and_milk_drinks"
to_assign[21,7] <- "L3_Flavored_milk_and_milk_drinks_fluid"
to_assign[21,8] <- "L4_Coffee_and_whey_flavors"
to_assign[21,9] <- "L5_"

#to_assign[22,4] #  "Chipotle dip, regular"
to_assign[22,5] <- "L1_Milk_and_Milk_Products"
to_assign[22,6] <- "L2_Creams_and_cream_substitutes"
to_assign[22,7] <- "L3_Sour_cream"
to_assign[22,8] <- "L4_Dip_sour_cream_base"
to_assign[22,9] <- "L5_"

#to_assign[23,4] #  "Ranch dip, regular"
to_assign[23,5] <- "L1_Milk_and_Milk_Products"
to_assign[23,6] <- "L2_Creams_and_cream_substitutes"
to_assign[23,7] <- "L3_Sour_cream"
to_assign[23,8] <- "L4_Dip_sour_cream_base"
to_assign[23,9] <- "L5_"

#to_assign[24,4] #  "Spinach and artichoke dip"
to_assign[24,5] <- "L1_Milk_and_Milk_Products"
to_assign[24,6] <- "L2_Creams_and_cream_substitutes"
to_assign[24,7] <- "L3_Sour_cream"
to_assign[24,8] <- "L4_Dip_sour_cream_base"
to_assign[24,9] <- "L5_"

#to_assign[25,4] #  "Seafood dip"
to_assign[25,5] <- "L1_Milk_and_Milk_Products"
to_assign[25,6] <- "L2_Creams_and_cream_substitutes"
to_assign[25,7] <- "L3_Sour_cream"
to_assign[25,8] <- "L4_Dip_sour_cream_base"
to_assign[25,9] <- "L5_"

#to_assign[26,4] #  "Salt, table" # LEAVE ALONE FOR NOW BUT LOOK AT MADHUR'S EXCEL SHEET (SAME W TACO SEASONING)


#to_assign[27,4] #  "Vinegar, cider"
to_assign[27,5] <- "L1_Fruits"
to_assign[27,6] <- "L2_Fruit_juices_and_nectars_excluding_citrus"
to_assign[27,7] <- "L3_Vinegar"
to_assign[27,8] <- "L4_"
to_assign[27,9] <- "L5_"

#to_assign[28,4] #  "Taco seasoning"

#to_assign[29,4] #  "Beef steak, NS as to cooking method, lean only eaten"
#to_assign[30,4] #  "Ground beef patty, cooked"
to_assign[29:30,5] <- "L1_Meat_Poultry_Fish_and_Mixtures"
to_assign[29:30,6] <- "L2_Beef"
to_assign[29,7]    <- "L3_Beef_steak"
to_assign[30,7]    <- "L3_Ground_beef_beef_patties_beef_meatballs"
to_assign[29:30,8] <- "L4_"
to_assign[29:30,9] <- "L5_"

#to_assign[31,4] #  "Chicken, NS as to part, rotisserie, skin eaten"
#to_assign[32,4] #  "Chicken, NS as to part, grilled without sauce, NS as to skin eaten"
#to_assign[33,4] #  "Chicken, NS as to part, grilled without sauce, skin eaten"
#to_assign[34,4] #  "Chicken, NS as to part, fried, coated, skin / coating eaten"
#to_assign[35,4] #  "Chicken, NS as to part, baked, coated, skin / coating eaten"
to_assign[31:35,5] <- "L1_Meat_Poultry_Fish_and_Mixtures"
to_assign[31:35,6] <- "L2_Poultry"
to_assign[31:35,7] <- "L3_Chicken"
to_assign[31:35,8] <- "L4_Chicken_NS_as_to_part"
to_assign[31:35,9] <- "L5_"

#to_assign[36,4] #  "Chicken breast, baked, broiled, or roasted, skin eaten, from raw"
#to_assign[37,4] #  "Chicken breast, baked, broiled, or roasted, skin not eaten, from raw"
#to_assign[38,4] #  "Chicken breast, baked, broiled, or roasted, skin not eaten, from raw"
#to_assign[39,4] #  "Chicken breast, baked or broiled, skin eaten, from pre-cooked"
#to_assign[40,4] #  "Chicken breast, baked or broiled, skin not eaten, from pre-cooked"
#to_assign[41,4] #  "Chicken breast, baked or broiled, skin not eaten, from fast food / restaurant"
#to_assign[42,4] #  "Chicken breast, baked, broiled, or roasted with marinade, skin not eaten, from raw"
#to_assign[43,4] #  "Chicken breast, rotisserie, skin not eaten"
#to_assign[44,4] #  "Chicken breast, grilled without sauce, skin eaten"
#to_assign[45,4] #  "Chicken breast, grilled without sauce, skin not eaten"
#to_assign[46,4] #  "Chicken breast, grilled with sauce, skin not eaten"
#to_assign[47,4] #  "Chicken breast, sauteed, skin eaten"
#to_assign[48,4] #  "Chicken breast, sauteed, skin not eaten"
#to_assign[49,4] #  "Chicken breast, fried, coated, skin / coating not eaten, from raw"
#to_assign[50,4] #  "Chicken breast, fried, coated, skin / coating eaten, from pre-cooked"
#to_assign[51,4] #  "Chicken breast, fried, coated, skin / coating eaten, from fast food / restaurant"
#to_assign[52,4] #  "Chicken breast, baked, coated, skin / coating eaten"
#to_assign[53,4] #  "Chicken leg, drumstick and thigh, baked or broiled, skin eaten"
#to_assign[54,4] #  "Chicken leg, drumstick and thigh, rotisserie, skin not eaten"
#to_assign[55,4] #  "Chicken drumstick, baked or broiled, skin eaten, from pre-cooked"
#to_assign[56,4] #  "Chicken thigh, baked, broiled, or roasted, skin eaten, from raw"
#to_assign[57,4] #  "Chicken thigh, fried, coated, skin / coating not eaten, from pre-cooked"
#to_assign[58,4] #  "Chicken thigh, fried, coated, skin / coating eaten, from restaurant"
#to_assign[59,4] #  "Chicken wing, baked, broiled, or roasted, from raw"
#to_assign[60,4] #  "Chicken wing, fried, coated, from fast food"
#to_assign[61,4] #  "Chicken wing, fried, coated, from restaurant"
#to_assign[62,4] #  "Chicken \"wings\" with hot sauce, from fast food / restaurant"
#to_assign[63,4] #  "Chicken \"wings\" with other sauces or seasoning, from fast food / restaurant"
#to_assign[64,4] #  "Chicken \"wings\", plain, from fast food / restaurant"
#to_assign[65,4] #  "Chicken \"wings\" with hot sauce, from precooked"
#to_assign[66,4] #  "Chicken \"wings\", plain, from precooked"
#to_assign[67,4] #  "Chicken \"wings\", boneless, with hot sauce, from fast food / restaurant"
#to_assign[68,4] #  "Chicken patty, breaded"
#to_assign[69,4] #  "Chicken nuggets, from fast food"
#to_assign[70,4] #  "Chicken nuggets, from restaurant"
#to_assign[71,4] #  "Chicken nuggets, from school lunch"
#to_assign[72,4] #  "Chicken nuggets, from frozen"
#to_assign[73,4] #  "Chicken nuggets, from other sources"
#to_assign[74,4] #  "Chicken tenders or strips, NFS"
#to_assign[75,4] #  "Chicken tenders or strips, breaded, from fast food"
#to_assign[76,4] #  "Chicken tenders or strips, breaded, from restaurant"
#to_assign[77,4] #  "Chicken tenders or strips, breaded, from frozen"
#to_assign[78,4] #  "Chicken tenders or strips, breaded, from other sources"
#to_assign[79,4] #  "Chicken, prepackaged or deli, luncheon meat"
to_assign[36:79,5] <- "L1_Meat_Poultry_Fish_and_Mixtures"
to_assign[36:79,6] <- "L2_Poultry"
to_assign[36:79,7] <- "L3_Chicken"
to_assign[36:52,8] <- "L4_Chicken_breast"
to_assign[53:54,8] <- "L4_Chicken_leg_drumstick_and_thigh"
to_assign[55,8]    <- "L4_Chicken_drumstick"
to_assign[56:58,8] <- "L4_Chicken_thigh"
to_assign[59:67,8] <- "L4_Chicken_wing"
to_assign[68,8]    <- "L4_Chicken_NS_as_to_part"
to_assign[69:73,8] <- "L4_Chicken_other_part_or_processed"
to_assign[74:78,8] <- "L4_Chicken_breast"
to_assign[79,8]    <- "L4_Chicken_other_part_or_processed"
to_assign[36:79,9] <- "L5_"

#to_assign[80,4] #  "Turkey, prepackaged or deli, luncheon meat"
#to_assign[81,4] #  "Turkey, prepackaged or deli, luncheon meat, reduced sodium"
to_assign[80:81,5] <- "L1_Meat_Poultry_Fish_and_Mixtures"
to_assign[80:81,6] <- "L2_Poultry"
to_assign[80:81,7] <- "L3_Turkey"
to_assign[80:81,8] <- "L4_Turkey_NS"
to_assign[80:81,9] <- "L5_"

#to_assign[82,4] #  "Chicken, shredded or pulled, with barbecue sauce"
to_assign[82,5] <- "L1_Meat_Poultry_Fish_and_Mixtures"
to_assign[82,6] <- "L2_Poultry"
to_assign[82,7] <- "L3_Chicken"
to_assign[82,8] <- "L4_Chicken_NS_as_to_part"
to_assign[82,9] <- "L5_"

#to_assign[83,4] #  "Spaghetti sauce with meat"
to_assign[83,5] <- "L1_Grain_Product"
to_assign[83,6] <- "L2_Pastas_cooked_cereals_rice"
to_assign[83,7] <- "L3_Pastas"
to_assign[83,8] <- "L4_Spaghetti"
to_assign[83,9] <- "L5_Spaghetti_cooked_NS"

#to_assign[84,4] #  "Cheeseburger, 1 small patty, with condiments, on bun, from fast food / restaurant (Burger King Cheeseburger)"
#to_assign[85,4] #  "Cheeseburger, 1 small patty, with condiments, on bun, from fast food / restaurant (McDonald's Cheeseburger)"
#to_assign[86,4] #  "Cheeseburger, 1 medium patty, with condiments, on bun, from fast food / restaurant (McDonald's Quarter Pounder with cheese)"
#to_assign[87,4] #  "Bacon cheeseburger, 1 small patty, with condiments, on bun, from fast food / restaurant"
#to_assign[88,4] #  "Double cheeseburger, 2 small patties, with condiments, on bun, from fast food / restaurant (McDonald's Double Cheeseburger)"
#to_assign[89,4] #  "Double bacon cheeseburger, 2 medium patties, with condiments, on bun, from fast food / restaurant (Wendy's Baconator)"
to_assign[84:89,5] <- "L1_Meat_Poultry_Fish_and_Mixtures"
to_assign[84:89,6] <- "L2_Beef"
to_assign[84:89,7] <- "L3_Ground_beef_beef_patties_beef_meatballs"
to_assign[84:89,8] <- "L4_"
to_assign[84:89,9] <- "L5_"

# 90  blt:  "L3_Tomato_sandwiches"  OR bacon OR "L3_Sandwiches_with_meat_poultry_fish"  OR "L3_Mixtures_mainly_grain_pasta_or_bread" and "L4_Wrap_sandwich"
# MADHUR SAID ASSIGN AS BACON

#to_assign[90,4] # "Bacon, lettuce, tomato, and cheese submarine sandwich, with spread"
to_assign[90,5] <- "L1_Meat_Poultry_Fish_and_Mixtures"
to_assign[90,6] <- "L2_Beef"
to_assign[90,7] <- "L3_Other_beef_items_beef_bacon_dried_beef_pastrami"
to_assign[90,8] <- "L4_"
to_assign[90,9] <- "L5_"

#to_assign[91,4] #  "Egg, whole, fried, NS as to fat added in cooking"
#to_assign[92,4] #  "Egg omelet or scrambled egg, NS as to fat added in cooking"
#to_assign[93,4] #  "Egg white omelet, scrambled, or fried, NS as to fat added in cooking"
to_assign[91:93,5] <- "L1_Eggs"
to_assign[91:93,6] <- "L2_Eggs"
to_assign[91:93,7] <- "L3_Chicken_eggs"
to_assign[91:93,8] <- "L4_Egg_whole_or_white"
to_assign[91:93,9] <- "L5_"

#to_assign[94,4] #  "Black, brown, or Bayo beans, dry, cooked, made with oil"
#to_assign[95,4] #  "Black, brown, or Bayo beans, canned, drained, fat not added in cooking"
#to_assign[96,4] #  "Pinto, calico, or red Mexican beans, dry, cooked, fat not added in cooking"
#to_assign[97,4] #  "Pinto, calico, or red Mexican beans, canned, drained, fat not added in cooking"
#to_assign[98,4] #  "Red kidney beans, canned, drained, fat not added in cooking"
#to_assign[99,4] #  "Refried beans, from restaurant"
to_assign[94:99,5] <- "L1_Dry_Beans_Peas_Other_Legumes_Nuts_and_Seeds"
to_assign[94:99,6] <- "L2_Legumes"
to_assign[94:99,7] <- "L3_Dried_beans"
to_assign[94:99,8] <- "L4_Beans_NS_to_type"
to_assign[94:95,9] <- "L5_Black_brown_bayo_or_fava"
to_assign[96:97,9] <- "L5_Pinto_calico_or_red_Mexican_beans"
to_assign[98,9]    <- "L5_Red_kidney_beans"
to_assign[99,9]    <- "L5_Pinto_calico_or_red_Mexican_beans"

#to_assign[100,4] #  "Hummus, flavored"                      ?????????????????
to_assign[100,5] <- "L1_Dry_Beans_Peas_Other_Legumes_Nuts_and_Seeds"
to_assign[100,6] <- "L2_Legumes"
to_assign[100,7] <- "L3_Dried_beans_mixtures"
to_assign[100,8] <- "L4_Dried_beans_mixtures"
to_assign[100,9] <- "L5_Bean_dips_and_sauces"

#to_assign[101,4] #  "Chickpeas, dry, cooked, made with oil" ?????????????????
to_assign[101,5] <- "L1_Dry_Beans_Peas_Other_Legumes_Nuts_and_Seeds"
to_assign[101,6] <- "L2_Legumes"
to_assign[101,7] <- "L3_Dried_beans"
to_assign[101,8] <- "L4_Beans_NS_to_type"
to_assign[101,9] <- "L5_Chickpea_beans"

#to_assign[102,4] #  "Edamame, cooked"                       "L5_Soybeans" ?
to_assign[102,5] <- "L1_Dry_Beans_Peas_Other_Legumes_Nuts_and_Seeds"
to_assign[102,6] <- "L2_Legumes"
to_assign[102,7] <- "L3_Dried_beans"
to_assign[102,8] <- "L4_Beans_NS_to_type"
to_assign[102,9] <- "L5_Soybeans"

#to_assign[103,4] #  "Almonds, salted"
#to_assign[104,4] #  "Almonds, unsalted"
#to_assign[105,4] #  "Almonds, flavored"
#to_assign[106,4] #  "Almonds, flavored"
#to_assign[107,4] #  "Cashews, lightly salted"
#to_assign[108,4] #  "Mixed nuts, with peanuts, lightly salted"
#to_assign[109,4] #  "Peanuts, unroasted"
to_assign[103:109,5] <- "L1_Dry_Beans_Peas_Other_Legumes_Nuts_and_Seeds"
to_assign[103:109,6] <- "L2_Nuts_nut_butters_and_nut_mixtures"
to_assign[103:109,7] <- "L3_Nuts"
to_assign[103:107,8] <- "L4_Nuts_NFS"
to_assign[108:109,8] <- "L4_Mixed_nuts_NFS"
to_assign[103:106,9] <- "L5_Almonds"
to_assign[107,9]     <- "L5_Cashew_nuts"
to_assign[108,9]     <- "L5_Mixed_nuts_NFS"
to_assign[109,9]     <- "L5_Peanuts"

#to_assign[110,4] #  "Pumpkin seeds, NFS"
#to_assign[111,4] #  "Chia seeds"
to_assign[110:111,5] <- "L1_Dry_Beans_Peas_Other_Legumes_Nuts_and_Seeds"
to_assign[110:111,6] <- "L2_Seeds_and_seed_mixtures"
to_assign[110:111,7] <- "L3_Seeds"
to_assign[110:111,8] <- "L4_Seeds_NS"
to_assign[110,9]     <- "L5_Pumpkin"
to_assign[111,9]     <- "L5_Chia" # i made this one up- there is no blank level 5 but i think it should be ok- can i label it?

#to_assign[112,4] #  "Garlic bread, from fast food / restaurant"
#to_assign[113,4] #  "Garlic bread, from fast food / restaurant"
#to_assign[114,4] #  "Garlic bread, with melted cheese, from fast food / restaurant"
to_assign[112:114,5] <- "L1_Grain_Product"
to_assign[112:114,6] <- "L2_Yeast"
to_assign[112:114,7] <- "L3_White_breads_rolls"
to_assign[112:114,8] <- "L4_Bread_with_additions"
to_assign[112:114,9] <- "L5_Bread_garlic_or_onion"

#to_assign[115,4] # "Roll, white, hamburger bun"
#to_assign[116,4] # "Breadsticks, soft, from frozen"
#to_assign[117,4] # "Roll, wheat or cracked wheat, hamburger bun"
#to_assign[118,4] # "Roll, whole wheat, hamburger bun"
#to_assign[119,4] # "Roll, whole grain white, hamburger bun"
to_assign[115:119,5] <- "L1_Grain_Product"
to_assign[115:119,6] <- "L2_Yeast"
to_assign[115,7]     <- "L3_White_breads_rolls"
to_assign[116,7]     <- "L3_Breadrolls_NFS"
to_assign[117,7]     <- "L3_Wheat_cracked_wheat_breads_rolls"
to_assign[118:119,7] <- "L3_Whole_wheat_breads_rolls"
to_assign[115,8]     <- "L4_White_breads_rolls"
to_assign[116,8]     <- "L4_"
to_assign[117,8]     <- "L4_Wheat_cracked_wheat_breads_rolls"
to_assign[118:119,8] <- "L4_Whole_wheat_breads"
to_assign[115,9]     <- "L5_Bread_white"
to_assign[116,9]     <- "L5_"
to_assign[117,9]     <- "L5_Bread_stick_whole_wheat"
to_assign[118:119,9] <- "L5_Whole_wheat_bread_or_pita"

#to_assign[120,4] # "Nutrition bar (Clif Kids Organic Zbar)"
to_assign[120,5] <- "L1_Grain_Product"
to_assign[120,6] <- "L2_Cakes_cookies_pies_pastries_bars"
to_assign[120,7] <- "L3_Bars"
to_assign[120,8] <- "L4_Cereal_bars_granola_bars"
to_assign[120,9] <- "L5_"

#to_assign[121,4] # "Graham crackers (Teddy Grahams)"
#to_assign[122,4] # "Crackers, breakfast biscuit"
#to_assign[123,4] # "Crackers, saltine, reduced sodium"
#to_assign[124,4] # "Crackers, butter, plain"
#to_assign[125,4] # "Crackers, butter (Ritz)"
#to_assign[126,4] # "Crackers, cheese (Cheez-It)"
#to_assign[127,4] # "Crackers, cheese (Goldfish)"
#to_assign[128,4] # "Crackers, sandwich, peanut butter filled (Ritz)"
#to_assign[129,4] # "Crackers, wheat, plain (Wheat Thins)"
#to_assign[130,4] # "Crackers, gluten free, plain"
to_assign[121:130,5] <- "L1_Grain_Product"
to_assign[121:130,6] <- "L2_Crackers_and_salty_snacks_from_grain"
to_assign[121:130,7] <- "L3_Nonsweet_crackers"
to_assign[121:130,8] <- "L4_Nonsweet_crackers"
to_assign[121,9]     <- "L5_Cracker_snack"
to_assign[123,9]     <- "L5_Crackers_saltine"        # OR LOW SODIUM CRACKERS ON LEVEL 3 (WITH NO SPECIFIC 4 OR 5)???
to_assign[124:125,9] <- "L5_Cracker_snack"
to_assign[126:127,9] <- "L5_Cracker_cheese"
to_assign[128,9]     <- "L5_Crackers_peanut_butter"
to_assign[129,9]     <- "L5_Cracker_wheat"
to_assign[130,9]     <- "L5_Cracker_gluten_free_NS"

to_assign[122,6] <- "L2_Quick_breads"
to_assign[122,7] <- "L3_Biscuits"
to_assign[122,8] <- "L4_Biscuits"
to_assign[122,9] <- "L5_Biscuit_or_crumpet"

#to_assign[131,4] # "Corn chips, plain"
#to_assign[132,4] # "Corn chips, flavored"
#to_assign[133,4] # "Corn chips, plain (Fritos)"
#to_assign[134,4] # "Cheese flavored corn snacks"
#to_assign[135,4] # "Cheese flavored corn snacks, reduced fat"
#to_assign[137,4] # "Cheese flavored corn snacks (Cheetos)"
to_assign[c(131:135,137),5] <- "L1_Grain_Product"
to_assign[c(131:135,137),6] <- "L2_Crackers_and_salty_snacks_from_grain"
to_assign[c(131:135,137),7] <- "L3_Salty_snacks_from_grain_products"
to_assign[c(131:135,137),8] <- "L4_Salty_snacks_from_grain_products"
to_assign[c(131:135,137),9] <- "L5_Salty_snacks_corn"

#to_assign[136,4] # "Tortilla chips, plain"
#to_assign[138,4] # "Tortilla chips, flavored"
#to_assign[139,4] # "Tortilla chips, nacho cheese flavor (Doritos)"
#to_assign[140,4] # "Tortilla chips, cool ranch flavor (Doritos)"
#to_assign[141,4] # "Tortilla chips, other flavors (Doritos)"
#to_assign[142,4] # "Tortilla chips, reduced fat, plain"
#to_assign[143,4] # "Tortilla chips, reduced fat, flavored"
to_assign[c(136,138:143),5] <- "L1_Grain_Product"
to_assign[c(136,138:143),6] <- "L2_Quick_breads"
to_assign[c(136,138:143),7] <- "L3_Cornbread_corn_muffins_tortillas"
to_assign[c(136,138:143),8] <- "L4_Tortillas"
to_assign[c(136,138:143),9] <- "L5_Tortillas_and_tacos"

#to_assign[144,4] # "Popcorn, NFS"
#to_assign[145,4] # "Popcorn, movie theater, with added butter"
#to_assign[146,4] # "Popcorn, movie theater, unbuttered"
#to_assign[147,4] # "Popcorn, popped in oil, unbuttered"
#to_assign[148,4] # "Popcorn, microwave, plain"
#to_assign[149,4] # "Popcorn, microwave, plain, light"
#to_assign[150,4] # "Popcorn, microwave, butter flavored"
#to_assign[151,4] # "Popcorn, microwave, butter flavored, light"
#to_assign[152,4] # "Popcorn, ready-to-eat packaged, NFS"
#to_assign[153,4] # "Popcorn, ready-to-eat packaged, plain"
#to_assign[154,4] # "Popcorn, ready-to-eat packaged, plain, light"
#to_assign[155,4] # "Popcorn, ready-to-eat packaged, butter flavored, light"
#to_assign[156,4] # "Pretzels, hard, plain, salted"
#to_assign[157,4] # "Pretzels, hard, plain, gluten free"
#to_assign[158,4] # "Pretzels, hard, white chocolate coated"
#to_assign[159,4] # "Pretzels, soft, ready-to-eat, salted, no butter"
#to_assign[160,4] # "Multigrain chips (Sun Chips)"
#to_assign[161,4] # "Snack mix, plain (Chex Mix)"
#to_assign[162,4] # "Cracker chips"
to_assign[144:162,5] <- "L1_Grain_Product"
to_assign[144:162,6] <- "L2_Crackers_and_salty_snacks_from_grain"
to_assign[144:162,7] <- "L3_Salty_snacks_from_grain_products"
to_assign[144:162,8] <- "L4_Salty_snacks_from_grain_products"
to_assign[144:155,9] <- "L5_Popcorn"
to_assign[156:159,9] <- "L5_Pretzels"
to_assign[160,9]     <- "L5_Salty_snacks_corn_wheat_multigrain_potatoes_or_pita"
to_assign[161,9]     <- "L5_Snack_mix"
to_assign[162,9]     <- "L5_"

#to_assign[163,4] # "Pancakes, gluten free, from frozen"
#to_assign[164,4] # "Pancakes, plain, from fast food / restaurant"
#to_assign[165,4] # "Pancakes, with fruit, from fast food / restaurant"
#to_assign[166,4] # "Pancakes, with chocolate, from fast food / restaurant"
#to_assign[167,4] # "Pancakes, from school, NFS"
#to_assign[168,4] # "Waffle, plain, from frozen"
#to_assign[169,4] # "Waffle, chocolate, from frozen"
#to_assign[170,4] # "Waffle, plain, from fast food / restaurant"
#to_assign[171,4] # "Waffle, from school, NFS"
#to_assign[172,4] # "French toast, plain, from fast food / restaurant"
#to_assign[173,4] # "French toast, from school, NFS"
to_assign[163:173,5] <- "L1_Grain_Product"
to_assign[163:173,6] <- "L2_Pancakes_waffles_French_toast_other"
to_assign[163:167,7] <- "L3_Pancakes"
to_assign[168:171,7] <- "L3_Waffles"
to_assign[172:173,7] <- "L3_French_toast"
to_assign[163:167,8] <- "L4_Pancakes"
to_assign[168:171,8] <- "L4_Waffles"
to_assign[172:173,8] <- "L4_"
to_assign[163:164,9] <- "L5_Pancakes_plain"
to_assign[165:166,9] <- "L5_Pancakes_with_fruit_or_chocolate"
to_assign[167,9]     <- "L5_Pancakes_plain"
to_assign[168,9]     <- "L5_Waffle_plain"
to_assign[169,9]     <- "L5_Waffle_with_fruit_nuts_chocolate"
to_assign[170:171,9] <- "L5_Waffle_plain"
to_assign[172:173,9] <- "L5_"

#to_assign[174,4] # "Pasta, cooked"
to_assign[174,5] <- "L1_Grain_Product"
to_assign[174,6] <- "L2_Pastas_cooked_cereals_rice"
to_assign[174,7] <- "L3_Pastas"
to_assign[174,8] <- "L4_Noodles"
to_assign[174,9] <- "L5_Noodles_cooked"

#to_assign[175,4] # "Cornmeal mush, NS as to fat added in cooking"
to_assign[175,5] <- "L1_Grain_Product"
to_assign[175,6] <- "L2_Pastas_cooked_cereals_rice"
to_assign[175,7] <- "L3_Cooked_cereals_rice"
to_assign[175,8] <- "L4_Cooked_cereals_rice"
to_assign[175,9] <- "L5_Grits_cooked_cornmeal_or_cornstarch"

#to_assign[176,4] # "Oatmeal, from fast food, plain"
#to_assign[177,4] # "Oatmeal, regular or quick, made with water, NS as to fat added in cooking"
#to_assign[178,4] # "Oatmeal, regular or quick, made with water, fat not added in cooking"
#to_assign[179,4] # "Oatmeal, regular or quick, made with milk, fat not added in cooking"
#to_assign[180,4] # "Oatmeal, regular or quick, made with non-dairy milk, fat not added in cooking"
#to_assign[181,4] # "Oatmeal, instant, maple flavored, fat not added in cooking"
#to_assign[182,4] # "Rice, white, cooked, NS as to fat added in cooking"
#to_assign[183,4] # "Rice, white, cooked, fat not added in cooking"
#to_assign[184,4] # "Rice, brown, cooked, NS as to fat added in cooking"
#to_assign[185,4] # "Rice, brown, cooked, fat not added in cooking"
to_assign[176:185,5] <- "L1_Grain_Product"
to_assign[176:185,6] <- "L2_Pastas_cooked_cereals_rice"
to_assign[176:185,7] <- "L3_Cooked_cereals_rice"
to_assign[176:185,8] <- "L4_Cooked_cereals_rice"
to_assign[176:181,9] <- "L5_Oatmeal"
to_assign[182:185,9] <- "L5_Rice"

#to_assign[186,4] # "Pizza, cheese, from school lunch, medium crust"
#to_assign[187,4] # "Pizza with pepperoni, from frozen, medium crust"
#to_assign[188,4] # "Pizza, with pepperoni, from school lunch, medium crust"
#to_assign[189,4] # "Pizza with meat other than pepperoni, from frozen, thick crust"
#to_assign[190,4] # "Pizza, with meat other than pepperoni, from school lunch, medium crust"
#to_assign[191,4] # "Pizza with meat and vegetables, from frozen, medium crust"
#to_assign[192,4] # "White pizza, cheese, thin crust"
#to_assign[193,4] # "White pizza, cheese, thick crust"
#to_assign[194,4] # "Pastry, egg and cheese filled"
#to_assign[195,4] # "Pastry, meat / poultry-filled"
to_assign[186:195,5] <- "L1_Grain_Product"
to_assign[186:195,6] <- "L2_Grain_mixtures_frozen_plate_meals_soups"
to_assign[186:195,7] <- "L3_Mixtures_mainly_grain_pasta_or_bread"
to_assign[186:195,8] <- "L4_Mixtures_mainly_grain_pasta_or_bread"
to_assign[186:191,9] <- "L5_Pizza"
to_assign[192:193,9] <- "L5_Pizza_no_cheese_or_white_pizza"
to_assign[194:195,9] <- "L5_Filled_pastry"

#to_assign[196,4] # "Macaroni or noodles with cheese, from restaurant"
to_assign[196,5] <- "L1_Grain_Product"
to_assign[196,6] <- "L2_Pastas_cooked_cereals_rice"
to_assign[196,7] <- "L3_Pastas"
to_assign[196,8] <- "L4_Macaroni"
to_assign[196,9] <- "L5_Macaroni_cooked"

#to_assign[197,4] # "Pasta with sauce, meatless, school lunch"
#to_assign[198,4] # "Pasta with tomato-based sauce, home recipe"
#to_assign[199,4] # "Pasta with sauce and meat, from school lunch"
#to_assign[200,4] # "Pasta with tomato-based sauce and meat, home recipe"
#to_assign[201,4] # "Pasta with tomato-based sauce and meat, ready-to-heat"
#to_assign[202,4] # "Pasta with tomato-based sauce, meat, and added vegetables, ready-to-heat"
#to_assign[203,4] # "Pasta with tomato-based sauce and poultry, restaurant"
#to_assign[204,4] # "Pasta with tomato-based sauce and poultry, home recipe"
#to_assign[205,4] # "Pasta with cream sauce, home recipe"
#to_assign[206,4] # "Pasta with cream sauce and added vegetables, restaurant"
#to_assign[207,4] # "Pasta with cream sauce and added vegetables, from home recipe"
#to_assign[208,4] # "Pasta with cream sauce and meat, restaurant"
#to_assign[209,4] # "Pasta with cream sauce and meat, home recipe"
#to_assign[210,4] # "Pasta with cream sauce and poultry, home recipe"
#to_assign[211,4] # "Pasta with cream sauce and poultry, ready-to-heat"
#to_assign[212,4] # "Pasta with cream sauce, poultry, and added vegetables, home recipe"
#to_assign[213,4] # "Pasta, whole grain, with tomato-based sauce, home recipe"
to_assign[197:213,5] <- "L1_Grain_Product"
to_assign[197:213,6] <- "L2_Pastas_cooked_cereals_rice"
to_assign[197:213,7] <- "L3_Pastas"
to_assign[197:204,8] <- "L4_Spaghetti"
to_assign[197:198,9] <- "L5_Spaghetti_cooked_NS"
to_assign[199:204,9] <- "L5_Spaghetti_with_meat"
to_assign[205:213,8] <- "L4_Noodles"
to_assign[205, 9]    <- "L5_Noodles_cooked"
to_assign[206:207,9] <- "L5_Noodles_cooked_vegetables"
to_assign[208:212,9] <- "L5_Noodles_with_meat"
to_assign[213,9]     <- "L5_Noodles_cooked_whole_wheat"


# question is what to prioritize? pasta, veggies, dairy, or meat?

#to_assign[214,4] # "Adobo, with rice"
#to_assign[215,4] # "Sushi roll, avocado"
#to_assign[216,4] # "Sushi roll, California"
#to_assign[217,4] # "Sushi roll, vegetable"
to_assign[214:217,5] <- "L1_Grain_Product"
to_assign[214:217,6] <- "L2_Grain_mixtures_frozen_plate_meals_soups"
to_assign[214:217,7] <- "L3_Mixtures_mainly_grain_pasta_or_bread"
to_assign[214:217,8] <- "L4_Mixtures_mainly_grain_pasta_or_bread"
to_assign[214,9]     <- "L5_Rice_dishes_or_paella"
to_assign[215:217,9] <- "L5_Sushi"

#to_assign[218,4] # "Onion soup mix, dry"
to_assign[218,5] <- "L1_Vegetables"
to_assign[218,6] <- "L2_Other_vegetables"
to_assign[218,7] <- "L3_Vegetable_soups"
to_assign[218,8] <- "L4_Vegetable_soups"
to_assign[218,9] <- "L5_Onions"

#to_assign[219,4] # "Guacamole with tomatoes"
to_assign[219,5] <- "L1_Fruits"
to_assign[219,6] <- "L2_Other_fruits"
to_assign[219,7] <- "L3_Mixtures_of_fruits_and_nonfruit_items"
to_assign[219,8] <- "L4_Mixtures_of_fruits_and_nonfruit_items"
to_assign[219,9] <- "L5_Guacamole_or_chutney"

#to_assign[220,4] # "Fruit smoothie, with whole fruit, no dairy"
#to_assign[221,4] # "Fruit smoothie, with whole fruit, no dairy, added protein"
to_assign[220:221,5] <- "L1_Fruits"
to_assign[220:221,6] <- "L2_Other_fruits"
to_assign[220:221,7] <- "L3_Mixtures_of_two_or_more_fruits"
to_assign[220:221,8] <- "L4_Fruit_smoothie"
to_assign[220:221,9] <- "L5_"

#[222] "Potato, boiled, from fresh, peel not eaten, fat not added in cooking"
#[223] "Potato, boiled, from fresh, peel eaten, fat added in cooking, NS as to type of fat"
#[224] "Potato, roasted, from fresh, peel eaten, NS as to fat added in cooking"
#[225] "Potato, roasted, from fresh, peel eaten, made with oil"
#[226] "Potato, roasted, from fresh, peel not eaten, NS as to fat added in cooking"
#[227] "Potato chips, NFS"
#[228] "Potato chips, plain"
#[229] "Potato chips, barbecue flavored"
#[230] "Potato chips, other flavored"
#[231] "Potato chips, ruffled, plain"
#[232] "Potato chips, ruffled, barbecue flavored"
#[233] "Potato chips, ruffled, sour cream and onion flavored"
#[234] "Potato chips, ruffled, cheese flavored"
#[235] "Potato chips, restructured, plain"
#[236] "Potato chips, restructured, flavored"
#[237] "Potato chips, baked, flavored"
#[238] "Potato, scalloped, NFS"
#[239] "Potato, scalloped, from fresh"
#[240] "Potato, french fries, restaurant"
#[241] "Potato, french fries, from frozen, fried"
#[242] "Potato, french fries, school"
#[243] "Potato, home fries, NFS"
#[244] "Potato, hash brown, from fast food"
#[245] "Potato, hash brown, from restaurant"
#[246] "Potato, mashed, from fresh, made with milk, with cheese"
#[247] "Potato, mashed, from fresh, made with milk, with gravy"
#[248] "Potato, mashed, from restaurant"
#[249] "Potato, mashed, from school lunch"
#[250] "Potato tots, school"
#[251] "Potato tots, frozen, baked"
#[252] "Potato, baked, peel eaten"
#[253] "Potato salad with egg, from restaurant"
#[254] "Potato salad, from restaurant"
to_assign[222:254,5] <- "L1_Vegetables"
to_assign[222:254,6] <- "L2_White_potatoes_and_Puerto_Rican_starchy_vegetables"
to_assign[222:226,7] <- "L3_White_potatoes_baked_and_boiled"
to_assign[222:226,8] <- "L4_White_potatoes_baked_and_boiled"
to_assign[222:223,9] <- "L5_White_potatoes_boiled"
to_assign[224:226,9] <- "L5_White_potatoes_roasted"
to_assign[227:237,7] <- "L3_White_potatoes_chips_and_sticks"
to_assign[227:237,8] <- "L4_White_potatoes_chips_and_sticks"
to_assign[227:237,9] <- "L5_White_potato_chips"
to_assign[238:239,7] <- "L3_White_potatoes_creamed_scalloped_au_gratin"
to_assign[238:239,8] <- "L4_White_potatoes_creamed_scalloped_au_gratin"
to_assign[238:239,9] <- "L5_White_potato_scalloped"
to_assign[240:245,7] <- "L3_White_potatoes_fried"
to_assign[240:245,8] <- "L4_White_potatoes_fried"
to_assign[240:242,9] <- "L5_White_potato_french_fries"
to_assign[243,9]     <- "L5_White_potato_home_fries"
to_assign[244:245,9] <- "L5_White_potato_hash_brown"
to_assign[246:249,7] <- "L3_White_potatoes_mashed_stuffed_puffs"
to_assign[246:249,8] <- "L4_White_potatoes_mashed_stuffed_puffs"
to_assign[246:249,9] <- "L5_White_potato_mashed"
to_assign[250:251,7] <- "L3_White_potatoes_fried"
to_assign[250:251,8] <- "L4_White_potatoes_fried"
to_assign[250:251,9] <- "L5_White_potato_hash_brown"
to_assign[252,7]     <- "L3_White_potatoes_baked_and_boiled"
to_assign[252,8]     <- "L4_White_potatoes_baked_and_boiled"
to_assign[252,9]     <- "L5_White_potatoes_baked"
to_assign[253:254,7] <- "L3_Potato_salad"
to_assign[253:254,8] <- "L4_Potato_salad"
to_assign[253,9]     <- "L5_Potato_salad_with_egg"
to_assign[254,9]     <- "L5_Potato_salad_with_dressing"

#[255] "Chard, cooked, made with butter"
#[256] "Kale, raw"
#[257] "Spinach, cooked, NS as to form, made with oil"
#[258] "Spinach, cooked, from fresh, made with butter"
#[259] "Broccoli, cooked, from fresh, fat not added in cooking"
#[260] "Broccoli, cooked, NS as to form, made with oil"
#[261] "Broccoli, cooked, from fresh, made with oil"
#[262] "Broccoli, cooked, from fresh, made with butter"
#[263] "Broccoli, cooked, from frozen, made with oil"
to_assign[255:263,5] <- "L1_Vegetables"
to_assign[255:263,6] <- "L2_Darkgreen_vegetables"
to_assign[255:258,7] <- "L3_Darkgreen_leafy_vegetables"
to_assign[255:258,8] <- "L4_Darkgreen_leafy_vegetables"
to_assign[255,9]     <- "L5_Chard"
to_assign[256,9]     <- "L5_Kale"
to_assign[257:258,9] <- "L5_Spinach"
to_assign[259:263,7] <- "L3_Darkgreen_nonleafy_vegetables"
to_assign[259:263,8] <- "L4_Broccoli"
to_assign[259:263,9] <- "L5_"

#[264] "Carrots, cooked, from fresh, fat not added in cooking"
#[265] "Carrots, cooked, NS as to form, made with butter"
#[266] "Carrots, cooked, from fresh, made with oil"
to_assign[264:266,5] <- "L1_Vegetables"
to_assign[264:266,6] <- "L2_Deepyellow_vegetables"
to_assign[264:266,7] <- "L3_Carrots"
to_assign[264:266,8] <- "L4_Carrots"
to_assign[264:266,9] <- "L5_Carrots_cooked"

#[267] "Sweet potato, baked, peel eaten, made with oil"
#[268] "Sweet potato, baked, peel not eaten, made with oil"
#[269] "Sweet potato, baked, peel not eaten, made with butter"
#[270] "Sweet potato fries, fast food / restaurant"
to_assign[267:270,5] <- "L1_Vegetables"
to_assign[267:270,6] <- "L2_Deepyellow_vegetables"
to_assign[267:270,7] <- "L3_Sweet_potatoes"
to_assign[267:269,8] <- "L4_Sweet_potatoes"
to_assign[270,8]     <- "L4_Sweet_potato_fried"
to_assign[267,9]     <- "L5_Sweet_potato_baked_peel_eaten"
to_assign[268:269,9] <- "L5_Sweet_potato_baked_peel_not_eaten"
to_assign[270,9]     <- "L5_"

#[271] "Tomatoes, cooked, from fresh, NS as to method"
to_assign[271,5] <- "L1_Vegetables"
to_assign[271,6] <- "L2_Tomatoes_and_tomato_mixtures"
to_assign[271,7] <- "L3_Tomatoes_cooked"
to_assign[271,8] <- "L4_Tomatoes_cooked"
to_assign[271,9] <- "L5_Tomatoes_cooked_NS"

#[272] "Asparagus, cooked, from fresh, made with butter"
#[273] "Beans, string, green, cooked, from fresh, made with oil"
#[274] "Beans, string, green, cooked, from fresh, made with butter"
#[275] "Brussels sprouts, cooked, from fresh, made with oil"
#[276] "Cabbage, green, cooked, fat not added in cooking"
#[277] "Cabbage, green, cooked, made with oil"
#[278] "Cabbage, green, cooked, made with butter"
#[279] "Cauliflower, cooked, from fresh, made with oil"
#[280] "Corn, yellow, cooked, from fresh, fat not added in cooking"
#[281] "Corn, yellow, cooked, from canned, made with butter"
#[282] "Garlic, cooked"
#[283] "Mushrooms, cooked, from fresh, fat not added in cooking"
#[284] "Mushrooms, cooked, NS as to form, made with oil"
#[285] "Mushrooms, cooked, from fresh, made with oil"
#[286] "Onions, cooked, from fresh, fat not added in cooking"
#[287] "Onions, cooked, from fresh, made with oil"
#[288] "Onions, cooked, from fresh, made with butter"
#[289] "Onions, cooked, from frozen, made with oil"
#[290] "Onions, green, cooked, from fresh, fat not added in cooking"
#[291] "Peppers, green, cooked, fat not added in cooking"
#[292] "Peppers, green, cooked, made with oil"
#[293] "Peppers, red, cooked, fat not added in cooking"
#[294] "Peppers, red, cooked, made with oil"
#[295] "Squash, summer, yellow or green, with tomato sauce, cooked, fat added in cooking"
to_assign[272:295,5] <- "L1_Vegetables"
to_assign[272:295,6] <- "L2_Other_vegetables"
to_assign[272:295,7] <- "L3_Other_vegetables_cooked"
to_assign[272:295,8] <- "L4_Other_vegetables_cooked"
to_assign[272,9]     <- "L5_Asparagus"
to_assign[273:274,9] <- "L5_Beans_lima_or_string"
to_assign[275,9]     <- "L5_Brussels_sprouts"
to_assign[276:278,9] <- "L5_Cabbage_green"
to_assign[279,9]     <- "L5_Cauliflower"
to_assign[280:281,9] <- "L5_Corn_or_cucumber"
to_assign[282,9]     <- "L5_Garlic"
to_assign[283:285,9] <- "L5_Mushrooms"
to_assign[286:290,9] <- "L5_Onions_palm_hearts_or_parsley"
to_assign[291:294,9] <- "L5_Peppers"
to_assign[295,9]     <- "L5_Squash"

#[296] "Ginger root, pickled"
to_assign[296,5] <- "L1_Vegetables"
to_assign[296,6] <- "L2_Other_vegetables"
to_assign[296,7] <- "L3_Other_vegetables_raw"
to_assign[296,8] <- "L4_Other_vegetables_raw"
to_assign[296,9] <- "L5_"

#[297] "Wasabi paste"
to_assign[297,5] <- "L1_Vegetables"
to_assign[297,6] <- "L2_Darkgreen_vegetables"
to_assign[297,7] <- "L3_Darkgreen_leafy_vegetables"
to_assign[297,8] <- "L4_Darkgreen_leafy_vegetables"
to_assign[297,9] <- "L5_Mustard_greens"

#[298] "Fruit and vegetable smoothie"
#[299] "Fruit and vegetable smoothie, added protein"
to_assign[298:299,5] <- "L1_Fruits"
to_assign[298:299,6] <- "L2_Other_fruits"
to_assign[298:299,7] <- "L3_Mixtures_of_two_or_more_fruits"
to_assign[298:299,8] <- "L4_Fruit_smoothie"
to_assign[298:299,9] <- "L5_"

#[300] "Agave liquid sweetener"
to_assign[300,5] <- "L1_Sugars_Sweets_and_Beverages"
to_assign[300,6] <- "L2_Sugars_and_sweets"
to_assign[300,7] <- "L3_Sugars_and_sugarsugar_substitute_blends"
to_assign[300,8] <- "L4_Sugars_and_sugarsugar_substitute_blends"
to_assign[300,9] <- "L5_Agave_liquid"

#[301] "Coffee, macchiato, sweetened"
#[302] "Coffee, Latte, with non-dairy milk"
#[303] "Coffee, Latte, flavored"
#[304] "Coffee, Latte, with non-dairy milk, flavored"
#[305] "Coffee, Latte, decaffeinated, nonfat, flavored"
#[306] "Iced Coffee, brewed"
#[307] "Coffee, Iced Latte"
#[308] "Coffee, Iced Latte, flavored"
#[309] "Coffee, Iced Latte, with non-dairy milk, flavored"
#[310] "Coffee, bottled/canned"
#[311] "Coffee, bottled/canned, light"
#[312] "Tea, hot, leaf, green"
#[313] "Tea, hot, leaf, green, decaffeinated"
#[314] "Tea, hot, chai, with milk"
#[315] "Tea, iced, brewed, black, pre-sweetened with sugar"
#[316] "Tea, iced, brewed, black, decaffeinated, pre-sweetened with sugar"
#[317] "Tea, iced, brewed, green, pre-sweetened with sugar"
#[318] "Lemonade, fruit flavored drink"
#[319] "Lemonade, fruit juice drink, light"
#[320] "Horchata beverage, made with water"
to_assign[301:320,5] <- "L1_Sugars_Sweets_and_Beverages"
to_assign[301:320,6] <- "L2_Nonalcoholic_beverages"
to_assign[301:311,7] <- "L3_Coffee"
to_assign[301:311,8] <- "L4_Coffee"
to_assign[301:311,9] <- "L5_Coffee_NS"  # NS to preparation method
to_assign[312:317,7] <- "L3_Tea"
to_assign[312:317,8] <- "L4_Tea"
to_assign[312:317,9] <- "L5_Tea_leaf"
to_assign[318:319,7] <- "L3_Fruit_drinks"
to_assign[318:319,8] <- "L4_Fruit_juice_drinks_and_fruitflavored_drinks"
to_assign[318:319,9] <- "L5_"
to_assign[320,7]     <- "L3_Sugars_and_sugarsugar_substitute_blends"
to_assign[320,8]     <- "L4_Sugars_and_sugarsugar_substitute_blends"
to_assign[320,9]     <- "L5_Sugar_white"

#[321] "Horchata beverage, made with milk"
to_assign[321,5] <- "L1_Milk_and_Milk_Products"
to_assign[321,6] <- "L2_Milks_and_milk_drinks"
to_assign[321,7] <- "L3_Flavored_milk_and_milk_drinks_fluid"
to_assign[321,8] <- "L4_Chololate_or_other_flavored"         # this idk
to_assign[321,9] <- "L5_"

#[322] "Hard cider"             - closest to wine
#[323] "Wine, table, rose"      - wine
#[324] "Sangria, red"           - cocktail
#[325] "Tequila"                - distilled liquors
to_assign[322:325,5] <- "L1_Sugars_Sweets_and_Beverages"
to_assign[322:325,6] <- "L2_Alcoholic_beverages"
to_assign[322:323,7] <- "L3_Wines"
to_assign[324,7]     <- "L3_Cocktails"
to_assign[325,7]     <- "L3_Distilled_liquors"
to_assign[322:325,8] <- "L4_"
to_assign[322:325,9] <- "L5_"

#[326] "Energy drink, sugar free"
to_assign[326,5] <- "L1_Sugars_Sweets_and_Beverages"
to_assign[326,6] <- "L2_Formulated_nutrition_beverages_energy_drinks_sports_drinks_function"
to_assign[326,7] <- "L3_"
to_assign[326,8] <- "L4_Energy_drinks"
to_assign[326,9] <- "L5_"

# to assign needs to matched with missing_taxonomy- which is the same but with duplicates
## this is what was done above: to_assign <- missing_taxonomy_data[!duplicated(missing_taxonomy_data[,"FoodID"]),]
all_assigned <- merge(x = missing_taxonomy_data, y = to_assign, by = "FoodID", all.x = TRUE)
nrow(all_assigned)

# BETTER ALTERNATIVE TO MAKE?
all_assigned <- all_assigned[c("FoodID", "X.x", "UserName.x", "Food_Description.x",
                               "Level1.y", "Level2.y", "Level3.y", "Level4.y", "Level5.y")]

colnames(all_assigned)
colnames(all_assigned)[2] = "original_index"
colnames(all_assigned)[3] = "UserName"
colnames(all_assigned)[4] = "Food_Description"
colnames(all_assigned)[5] = "Level1"
colnames(all_assigned)[6] = "Level2"
colnames(all_assigned)[7] = "Level3"
colnames(all_assigned)[8] = "Level4"
colnames(all_assigned)[9] = "Level5"

# forget: write.csv(to_assign,"~/Desktop/Greathouse/VitaminDstudy/Entered_Taxonomy.csv")
write.csv(all_assigned,"~/Desktop/Greathouse/VitaminDstudy/all_assigned.csv")
